// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPCrfpaLEB7c8vRbBMn_BtLS1NU2izgek',
    appId: '1:1059095309463:web:b7ad2a563324bf2abbcdd2',
    messagingSenderId: '1059095309463',
    projectId: 'fastcampus-market-bbbd3',
    authDomain: 'fastcampus-market-bbbd3.firebaseapp.com',
    storageBucket: 'fastcampus-market-bbbd3.appspot.com',
    measurementId: 'G-7BEBGTM5Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiOwi6a-FB503PBjqQdvefF8VhzxUYDbc',
    appId: '1:1059095309463:android:54e9e6ec31be8b80bbcdd2',
    messagingSenderId: '1059095309463',
    projectId: 'fastcampus-market-bbbd3',
    storageBucket: 'fastcampus-market-bbbd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSJSUaV7md0NUFJl0bFCL2PMuVp07p3Xk',
    appId: '1:1059095309463:ios:b099b205012c3091bbcdd2',
    messagingSenderId: '1059095309463',
    projectId: 'fastcampus-market-bbbd3',
    storageBucket: 'fastcampus-market-bbbd3.appspot.com',
    iosClientId: '1059095309463-kr9avp2ov27t1t62633r38ifm3fo55g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.part5FastcampusMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSJSUaV7md0NUFJl0bFCL2PMuVp07p3Xk',
    appId: '1:1059095309463:ios:b099b205012c3091bbcdd2',
    messagingSenderId: '1059095309463',
    projectId: 'fastcampus-market-bbbd3',
    storageBucket: 'fastcampus-market-bbbd3.appspot.com',
    iosClientId: '1059095309463-kr9avp2ov27t1t62633r38ifm3fo55g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.part5FastcampusMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPCrfpaLEB7c8vRbBMn_BtLS1NU2izgek',
    appId: '1:1059095309463:web:519104158cfb8cb4bbcdd2',
    messagingSenderId: '1059095309463',
    projectId: 'fastcampus-market-bbbd3',
    authDomain: 'fastcampus-market-bbbd3.firebaseapp.com',
    storageBucket: 'fastcampus-market-bbbd3.appspot.com',
    measurementId: 'G-6TPMJW2ZB9',
  );
}
