// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHMAFWLIAUnPBV3vTKSWhFNqyfqwfUr0Q',
    appId: '1:275752523351:android:64efa8a2aff346b284f512',
    messagingSenderId: '275752523351',
    projectId: 'local-basic-test-1022',
    databaseURL: 'https://local-basic-test-1022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'local-basic-test-1022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAbeFAcso2ErgB4QbrYc3-RVusEJ0Nzaw',
    appId: '1:275752523351:ios:c9a57336d6fa522e84f512',
    messagingSenderId: '275752523351',
    projectId: 'local-basic-test-1022',
    databaseURL: 'https://local-basic-test-1022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'local-basic-test-1022.appspot.com',
    iosBundleId: 'com.example.part5FirebaseBasic',
  );
}
